  /characters:
    get:
      summary: Lista personagens de Star Wars
      parameters:
        - name: name
          in: query
          schema:
            type: string
        - name: gender
          in: query
          schema:
            type: string
        - name: order_by
          in: query
          schema:
            type: string
            enum: [name, height]
        - name: order
          in: query
          schema:
            type: string
            enum: [asc, desc]
        - name: limit
          in: query
          schema:
            type: integer
      responses:
        '200':
          description: Lista de personagens
        '400':
          description: Parâmetros inválidos
